### test index
GET http://localhost:8080/

### test file
GET http://localhost:8080/Cargo.toml

### test file2
GET http://localhost:8080/fixtures/std.txt

### test tower
GET http://localhost:8080/tower/Cargo.toml
